message(STATUS "CMAKE_CURRENT_SOURCE_DIR : ${CMAKE_CURRENT_LIST_DIR}")
message(STATUS "Try to install Tetwild libs .....")
if (WIN32)
    set(FILE_EXTENSION lib)
else()
    set(FILE_EXTENSION a)
endif ()
FILE(GLOB_RECURSE lib_list *.${FILE_EXTENSION})
list(LENGTH lib_list lib_list_count)
FOREACH(_LIB ${lib_list})
    message(STATUS ${_LIB})
    get_filename_component(FN ${_LIB} NAME)
    get_filename_component(FD ${_LIB} DIRECTORY)
    get_filename_component(FDN ${FD} NAME)
    message(STATUS "FN : ${FN}")
    message(STATUS "FD : ${FD}")
    message(STATUS "FDN : ${FDN}")
    if("${FDN}" STREQUAL "Debug")
    	file(INSTALL ${_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/Debug)
    elseif("${FDN}" STREQUAL "Release")
        file(INSTALL ${_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/Release)
    else()
        file(INSTALL ${_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
    endif()
ENDFOREACH()

file(GLOB_RECURSE PYTETWILD_LIB ${CMAKE_CURRENT_BINARY_DIR}/*pytetwild.so
                                ${CMAKE_CURRENT_BINARY_DIR}/*pytetwild.dll
                                ${CMAKE_CURRENT_BINARY_DIR}/*pytetwild.pyd)
message(STATUS ${PYTETWILD_LIB})
file(INSTALL ${PYTETWILD_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX}/python/pytetwild)
